import React from "react";
import type { Metadata } from "next";

import { Navbar, Footer } from "@school/components";

import "./globals.css";

export const metadata: Metadata = {
  title: { template: "%s | Driving School", default: "Home | Driving School" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="" suppressHydrationWarning>
        <Navbar />

        <div>{children}</div>

        <Footer />
      </body>
    </html>
  );
}
